spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 7MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-url: ${KAKAO_REDIRECT_URL}
    client-secret: ${KAKAO_SECRET}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    redirect-url: ${NAVER_REDIRECT_URL}
    client-secret: ${NAVER_SECRET}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
      auto: false
    stack:
      auto: false
